### ISSUE TITLE
[PaperSpigot] "Patching the server failed"

### ISSUE THREAD

**Issue by MelonCode** [HellFirePvP/CustomMobs#12]
Hello. Trying to use CustomMobs 3.7 on latest PaperSpigot, but getting "Patching the server failed." error. 
Is this fork unsupported?

**Comment by HellFirePvP** [comment]
PaperSpigot is not supported for now. I might provide solutions for PaperSpigot users soon, but i cannot provide any exact date.

**Comment by MelonCode** [comment]
Sad. Thanks for fast reply.

**Comment by HellFirePvP** [comment]
Wrote a workaround in the next version.
