### ISSUE TITLE
Health of a mob cant go above 2048?

### ISSUE THREAD

**Issue by xPhTx3** [HellFirePvP/CustomMobs#13]
when i add 2048 health it works fine but at 2049 it turns into a normal skeleton (it was a wither skeleton)

**Comment by HellFirePvP** [comment]
Please take a look at the spigot server configuration. the maximum possible health is set there and by default it's 2048. Change the max value there if you want it higher than 2048.

**Comment by HellFirePvP** [comment]
Since this issue is not on my end i'm just sending a message to the user in the next version in case you're trying to set the health above spigot's configuration. not much more i can do there.
