### ISSUE TITLE
Spawning Limits (/cmob limit <Name> <limit/-1/infinite>)

### ISSUE THREAD

**Issue by Peashooter101** [HellFirePvP/CustomMobs#18]
The command listed for limiting custom mob spawning (/cmob limit) imposes a limitation on the mobs spawned in total, regardless if they no longer exist in the server or do.

I would understand if this is an intended feature, allowing only a certain number of mobs to have spawned in the server, however if it is intended I propose another command.

The issue I have with this command is that it applies the limitations of the mobs spawned to how many times it has spawned a mob. Should I set the limit value to 10, it would spawn ten mobs and stop spawning, yes. However, the spawning limitation prevents it from spawning more after any of the ten are killed or no longer exist.

The command I assumed it was, was a limitation on how many can be in the server at one time. For instance, should I have set the value to 10, then ten mobs would spawn and then stop spawning until one is killed. Once it is killed, the spawners that would be set up would replace the dead one. That is my assumption of how it worked.

Should this be an intended feature by you, I understand, however I feel a "current limitation" or a limitation on how many mobs are in the world/server currently is more useful and applicable for this plugin (especially since my goal was to ensure dungeons aren't overrun and that only one boss mob remains in a room at once).

I have attempted numerous ways to go around it such as using an execute command on an entity or player nearby to force it to summon on demand. There is no "spawn custom mob at location" command so that would be another suggestion I have for this plugin, as well as command block integration.

Thank you for your consideration,
~ Jared S. (Peashooter101)

**Comment by HellFirePvP** [comment]
The feature's intention is to limit the mobs' current amount of instances not the overall spawned amount. Or to say it in a different way: If the limit is set to 10 for mob X, only 10 living instances of that mob are allowed to live at the same time.

And yea that is kinda broken atm. The source for this issue is the same as #17 and will be fixxed in the next update.

Also there is a command to spawn a custommob at a specific position that can be executed via console or commandblock. Have a look at /ccmob spawn.

**Comment by HellFirePvP** [comment]
Should be fixxed. Reopen if the issue still exists with 4.1

**Comment by Peashooter101** [comment]
Issue still remains. Not fixed. Used version 4.12

**Comment by HellFirePvP** [comment]
You're using CustomMobs along with some other plugins i guess? Since this issue is fixxed on my dev server on 4., i assume some other plugin causes this... So could you please try and narrow it down what plugin interferes here? - Ofc all under the assumption you're using CustomMobs together with other plugins.. (Excluding WorldGuard, WorldEdit, as well as Factions and its MassiveCore - those are included in my dev server and don't cause this)

**Comment by Peashooter101** [comment]
The following plugins were installed on my server:
CoreProtect, WorldEdit, LampControl, Essentials, ClearChat, Holograms, WorldGuard, KitAdder, CustomMobs, EssentialsProtect,EssentialsGeoIP, EssentialsChat, PermissionsEx, CS-CoreLib, mcMMO, Vault, EssentialsSPawn, Lores, CustomEnchants, MassiveCore, ChestShop, CreativeGates, SilkSpawners, Citizens, PhatLoots, PlayerVaults, QuestWorld, Denizen, Sentry (Denizen extension)

Do you not recognize any of those plugins and believe that any of them could cause an issue? Attempting to narrow it down is a long shot unless you give me a list of suspects out of that list.

Also, I used QuestWorld to run the limit command again so that when the player successfully kills a boss mob for example which requires only 1 to be active at a time, the limit is reset and it should respawn but that did not work so...

**Comment by Peashooter101** [comment]
I tested the following plugins by disabling them. Only one of the plugins from that list was off at a time.
HoloGrams, CS-CoreLib, mcMMO, Vault, CustomEnchants, SilkSpawners, Citizens, PlayerVaults, QuestWorld, Denizen

**Comment by HellFirePvP** [comment]
It's hard to say what plugin could be responsible for this. Also, unfortunately, i don't have access to my main computer until sunday which makes it kinda hard for me to track down these bugs right now. I'll look into it as soon as i can.

**Comment by Peashooter101** [comment]
If this would be of any assistance, I am running Spigot for Minecraft 1.9 using API Version 1.9-R0.1-Snapshot

**Comment by HellFirePvP** [comment]
I can't reproduce it. Under any circumstances with just CustomMobs and a 1.10 or a 1.9 server environment. I'm very sorry, i guess you could narrow it down by removing plugins one by one, but i can't reproduce it.

**Comment by Peashooter101** [comment]
Does this plugin have any dependencies that I forgot to include? I am running a Spigot 1.9 using API Version 1.9-R-0.1-SNAPSHOT with JUST the Custom Mobs plugin and it is legitimately not working.

**Comment by HellFirePvP** [comment]
That is one awkward thing then. If you don't mind, can you pm me the server you're on? I'd like join you and find out the source of this myself. :P

**Comment by Peashooter101** [comment]
chaoscraft.hosthavoc.com:25576

**Comment by Peashooter101** [comment]
Server is currently whitelisted. Added HellFirePvP to the whitelist.

**Comment by HellFirePvP** [comment]
Unfortunately, there is no way for me to add TabComplete support for 1.9.R1 servers. So well. the version uploaded to spigot works properly with 1.9.R1 now, but without TabComplete...
