### ISSUE TITLE
Fire Proofing (/cmob fireproof <Name> <true/false>)

### ISSUE THREAD

**Issue by Peashooter101** [HellFirePvP/CustomMobs#19]
The command /cmob fireproof does not add fireproofing to the mobs. The mobs which are spawned in with this property on true still take damage from lava, fire, etc.

**Comment by HellFirePvP** [comment]
That is kinda new to me that this doesn't work. I'll have a look at it again.

**Comment by HellFirePvP** [comment]
Should be fixxed with 4.1
