### ISSUE TITLE
An Internal Error occurred while preforming this command

### ISSUE THREAD

**Issue by saolover** [HellFirePvP/CustomMobs#22]
It keeps saying that there was an internal error. The only plugins I have installed are CustomMobs and worldedit... Please help me.

**Comment by HellFirePvP** [comment]
Could you please attach the stacktrace printed in the console and please say what command you're trying to execute

**Comment by saolover** [comment]
It happens after almost any commands used to edit the custom mobs. 
Example: /cm health GuardDog 20
And I am new to bug reporting. How do I attach a stacktrace? Sorry I should know this.

**Comment by HellFirePvP** [comment]
You're not using spigot i assume. yeeeaa.. i still need to remove the hard dependency for spigot in that command, i forgot about that doing v4.14

Well whenever you cause an error or whatever, there's something popping up in the console saying something like "an unexpected exception occured" followed by a ton of - i guess to you "cryptic" - lines that tell me/you where exactly the error occured.

**Comment by saolover** [comment]
Ok so the fix is to use bukkit?

**Comment by HellFirePvP** [comment]
At the moment, spigot

**Comment by HellFirePvP** [comment]
Should be fixxed in v4.15
